### ISSUE TITLE
未投票时的展示有问题

### ISSUE THREAD

**Issue by rayfeng** [blackChef/abcyui#1]
未投票时的展示有问题
![image](https://user-images.githubusercontent.com/1352924/52278199-6f8cb580-2991-11e9-8014-07fe40e267ac.png)

**Comment by blackChef** [comment]
https://github.com/blackChef/abcyui/commit/262eefd963a1662c72027d9a82f9ef63575c083c

这样应该就行了。忘了处理 0 了。
